// Auto-generated by moshi-hook. Update with care.
//
// OpenCode 2 runs plugins' server half in one shared background service, so
// that process's TMUX_PANE/HERDR_PANE_ID belong to whichever terminal started
// the service, not to the TUI showing a session. This TUI half runs inside
// each TUI process, whose environment is the pane's own, and tells moshi-hook
// which session that pane currently shows. The daemon makes the binding
// exclusive: a pane shows one session, and a session is shown by the TUI that
// selected it last.
import { createConnection } from "node:net"
import { homedir } from "node:os"
import { join as pathJoin } from "node:path"
import { spawnSync } from "node:child_process"

const ROUTE_POLL_INTERVAL_MS = 250
const RETRY_DELAYS_MS = [250, 1000, 3000]

// Mirrors internal/config.SocketPath.
function socketPath() {
  if (process.env.MOSHI_SOCKET_PATH) return process.env.MOSHI_SOCKET_PATH
  if (process.platform === "darwin") return pathJoin(homedir(), "Library", "Application Support", "Moshi", "moshi-hook.sock")
  if (process.platform === "win32") return "\\\\.\\pipe\\moshi-hook"
  if (process.env.XDG_RUNTIME_DIR) return pathJoin(process.env.XDG_RUNTIME_DIR, "moshi-hook.sock")
  return "/tmp/moshi-hook.sock"
}

// Resolves true only when the daemon acknowledged the envelope.
function send(envelope) {
  return new Promise((resolve) => {
    let settled = false
    const chunks = []
    const finish = (ok) => {
      if (settled) return
      settled = true
      clearTimeout(timer)
      try { sock.destroy() } catch {}
      resolve(ok)
    }
    const timer = setTimeout(() => finish(false), 1000)
    timer.unref?.()
    const sock = createConnection({ path: socketPath() })
    sock.once("error", () => finish(false))
    sock.once("connect", () => {
      sock.write(JSON.stringify(envelope) + "\n")
      sock.end()
    })
    sock.on("data", (b) => chunks.push(b))
    sock.once("close", () => {
      try { finish(JSON.parse(Buffer.concat(chunks).toString("utf8").split("\n")[0]).type === "ack") } catch { finish(false) }
    })
  })
}

// Same detection order as the server plugin's resolveTerminalContext.
function terminalContext() {
  const env = process.env
  const context = { terminalKind: "" }
  if (env.TMUX && env.TMUX_PANE) {
    const args = ["display-message", "-p", "-t", env.TMUX_PANE, "#S\t#I"]
    try {
      const out = spawnSync("tmux", args, { encoding: "utf8", timeout: 500 })
      const [session = "", window = ""] = String(out.stdout || "").trim().split("\t", 2)
      if (session) {
        const comma = env.TMUX.indexOf(",")
        Object.assign(context, {
          terminalKind: "tmux", tmuxSession: session, tmuxWindow: window, tmuxPane: env.TMUX_PANE,
          tmuxSocket: comma > 0 ? env.TMUX.slice(0, comma) : "",
        })
        return context
      }
    } catch {}
  }
  if (env.HERDR_ENV === "1" && env.HERDR_PANE_ID) {
    return Object.assign(context, {
      terminalKind: "herdr", herdrSession: env.HERDR_SESSION || "", herdrPane: env.HERDR_PANE_ID,
      herdrWorkspaceId: env.HERDR_WORKSPACE_ID || "", herdrTabId: env.HERDR_TAB_ID || "",
    })
  }
  if (env.ZELLIJ_PANE_ID) {
    return Object.assign(context, { terminalKind: "zellij", zellijSession: env.ZELLIJ_SESSION_NAME || "", zellijPane: env.ZELLIJ_PANE_ID })
  }
  return context
}

async function setup(api) {
  const terminal = terminalContext()
  // Without a pane there is nothing to bind; the daemon falls back to
  // session-only tracking exactly as before.
  if (!terminal.terminalKind) return

  let disposed = false
  let reported // session id last acknowledged for this pane ("" = none)
  let wanted
  let attempt = 0
  let retryAt = 0
  let inFlight = false

  function selectedSession() {
    const route = api.ui.router.current()
    if (!route || route.type !== "session" || !route.sessionID) return ""
    // Subagent views belong to the root conversation's pane.
    try { return api.data.session.root(route.sessionID) || route.sessionID } catch { return route.sessionID }
  }

  async function sync() {
    if (disposed || inFlight) return
    const sessionID = selectedSession()
    if (sessionID !== wanted) {
      wanted = sessionID
      attempt = 0
      retryAt = 0
    }
    if (wanted === reported || Date.now() < retryAt) return
    const info = wanted ? api.data.session.get(wanted) : undefined
    inFlight = true
    const target = wanted
    const ok = await send({
      type: "session.bind",
      source: "opencode",
      sessionId: target,
      cwd: info?.location?.directory || "",
      agentPid: process.pid,
      ...terminal,
    }).finally(() => { inFlight = false })
    if (ok) {
      reported = target
      return
    }
    const delay = RETRY_DELAYS_MS[Math.min(attempt, RETRY_DELAYS_MS.length - 1)]
    attempt += 1
    retryAt = Date.now() + delay
  }

  const timer = setInterval(() => void sync(), ROUTE_POLL_INTERVAL_MS)
  void sync()
  return () => {
    disposed = true
    clearInterval(timer)
  }
}

export default { id: "moshi-hooks-tui", setup }
