words = [
  "bashls",
  "cssls",
  "dockerls",
  "golangci",
  "gopls",
  "jsonls",
  "launchable",
  "lspconfig",
  "phpactor",
  "prismals",
  "stylua",
  "taplo",
  "terraformls",
  "vtsls",
  "yamlls",
]
