local a = require('rmarganti.colors.abstractions')

return {
    -- ['@annotation'] = {},
    -- ['@boolean'] = { fg = a.base },
    -- ['@conditional'] = { fg = a.base },
    -- ['@constant.builtin'] = { fg = a.base },
    -- ['@constant.macro'] = { fg = a.base },
    ['@constant'] = { fg = a.plus2 },
    ['@constructor'] = { fg = a.plus3 },
    -- ['@currentscope'] = {},
    -- ['@definition'] = {},
    -- ['@definitionusage'] = {},
    -- ['@emphasis'] = {},
    ['@error'] = { fg = a.error }, -- For syntax/parser errors.
    -- ['@exception'] = { fg = a.base },
    ['@field'] = { fg = a.plus2 },
    -- ['@float'] = { fg = a.base },
    ['@function.builtin'] = { fg = a.plus2 },
    -- ['@function.macro'] = { fg = a.base },
    ['@function'] = { fg = a.plus2 },
    -- ['@function.call'] = { fg = a.plus2 },
    ['@include'] = { fg = a.base },
    -- ['@keyword'] = { fg = a.base },
    -- ['@keyword.function'] = { fg = a.base },
    -- ['@label'] = { fg = a.base },
    ['@literal'] = { fg = a.plus1 },
    ['@method'] = { fg = a.plus2 },
    -- ['@method.call'] = { fg = a.plus2 },
    ['@namespace'] = { fg = a.plus3 },
    -- ['@number'] = { fg = a.base },
    -- ['@operator'] = { fg = a.base },
    -- ['@parameter'] = { fg = a.base },
    -- ['@parameterreference'] = { fg = a.base_high },
    ['@property'] = { fg = a.base },
    ['@punctuation.bracket'] = { fg = a.base },
    ['@punctuation.delimiter'] = { fg = a.base },
    ['@punctuation.special'] = { fg = a.base },
    -- ['@repeat'] = { fg = a.base },
    -- ['@string'] = { fg = a.base },
    -- ['@string.escape'] = { fg = a.base },
    -- ['@string.regex'] = { fg = a.base },
    -- ['@strong'] = {},
    -- ['@structure'] = { fg = a.base },
    -- ['@symbol'] = { fg = a.base},
    ['@tag'] = { fg = a.plus3 }, -- Tags like html tag names.
    ['@tag.attribute'] = { fg = a.plus2 }, -- Tag delimiter like `<` `>` `/`
    ['@tag.delimiter'] = { fg = a.base }, -- Tag delimiter like `<` `>` `/`
    -- ['@text'] = {},
    -- ['@title'] = {},
    -- ['@type'] = { fg = a.plus1 },
    -- ['@type.builtin'] = { fg = a.plus1 },
    -- ['@uri'] = {},
    -- ['@underline'] = {},
    ['@variable'] = { fg = a.plus3 },
    ['@variable.builtin'] = { fg = a.plus3 },
}
