menu_bar = false
prompt_save_view_preferences = false
theme = "custom"
transparent_background = true
watch = true

[keybindings]
"hunk.review.scrollCodeLeft" = ["h", "shift+h", "left", "shift+left"]
"hunk.review.scrollCodeRight" = ["l", "shift+l", "right", "shift+right"]
"hunk.view.toggleLineNumbers" = "i"

[custom_theme]
base = "github-dark-default"
label = "Neverforest"
background = "#1d2226"
panel = "#1d2226"
panelAlt = "#1d2226"
border = "#515a5b"
accent = "#aeccc6"
accentMuted = "#30383f"
text = "#d3c6aa"
muted = "#515a5b"
addedBg = "#222826"
removedBg = "#2b2020"
movedAddedBg = "#292720"
movedRemovedBg = "#292720"
contextBg = "#1d2226"
addedContentBg = "#354033"
removedContentBg = "#44302f"
contextContentBg = "#1d2226"
addedSignColor = "#a2ccae"
removedSignColor = "#e67e80"
lineNumberBg = "#1d2226"
lineNumberFg = "#515a5b"
selectedHunk = "#45585f"
badgeAdded = "#a2ccae"
badgeRemoved = "#e67e80"
badgeNeutral = "#9da9a0"
fileNew = "#a2ccae"
fileDeleted = "#e67e80"
fileRenamed = "#dbbc7f"
fileModified = "#dbbc7f"
fileUntracked = "#a2ccae"
noteBorder = "#87b5c1"
noteBackground = "#23292e"
noteTitleBackground = "#2a3137"
noteTitleText = "#d3c6aa"

[custom_theme.syntax]
default = "#d3c6aa"
keyword = "#77817d"
string = "#bec8b5"
comment = "#515a5b"
number = "#bec8b5"
function = "#a2ccae"
property = "#bec8b5"
type = "#aeccc6"
variable = "#f6f3ed"
operator = "#9da9a0"
punctuation = "#9da9a0"
